####################################################################
# Set hostname
####################################################################
- name: Set hostname
  hostname:
    name: '{{ inventory_hostname }}'

- name: add myself to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ inventory_hostname }}'
    state: present

####################################################################
# Setup Timedatectl
####################################################################
- name: Set time to {{ timezone }}
  timezone:
    name: '{{ timezone }}'

####################################################################
# Apt update
####################################################################
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

####################################################################
# Slack notification
####################################################################
- name: Send slack notification when done
  slack:
    token: "{{ slack_token }}"
    msg: '{{ ansible_nodename }}:{{ ansible_default_ipv4.address }} - Init setup - {{ ansible_nodename }}'
    channel: "{{ slack_channel }}"
  when: slack_token is undefined